export const CHANGE_CATEGORY = "CHANGE_CATEGORY";
export const GET_CATEGORIES_SUCCES = "GET_CATEGORIES_SUCCES";
export const GET_PRODUCTS_SUCCES = "GET_PRODUCTS_SUCCES";
export const ADD_PRODUCTS_TO_SUMMARY = "ADD_PRODUCTS_TO_SUMMARY";
export const REMOVE_PRODUCT_FROM_SUMMARY = "REMOVE_PRODUCT_FROM_SUMMARY";
export const REMOVE_CART_SUMMARY = "REMOVE_CART_SUMMARY";

export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
